import { db } from "../db.js";
import * as schema from "../schema/schema.js";
import bcrypt from "bcrypt";

async function hashUserPassword(userData) {
  let newUserData = [];
  for (const user of userData) {
    const hashedPass = await bcrypt.hash(user.password, 10);
    newUserData.push({
      ...user,
      password: hashedPass,
    });
  }
  return newUserData;
}

async function seed() {
  console.log("Seeding starts ...");
  //   const organization_data = [
  //     { id: 1, name: "TechNova Solutions", location: "Bangalore" },
  //     { id: 2, name: "EduSphere University", location: "Pune" },
  //     { id: 3, name: "HealthBridge Hospitals", location: "Hyderabad" },
  //     { id: 4, name: "AeroLink Aviation Pvt. Ltd.", location: "Mumbai" },
  //     { id: 5, name: "GreenLeaf Organics", location: "Kolkata" },
  //     { id: 6, name: "NextGen Financial Services", location: "Delhi" },
  //     { id: 7, name: "UrbanHomes Real Estate", location: "Chennai" },
  //     { id: 8, name: "CineWave Studios", location: "Mumbai" },
  //     { id: 9, name: "ByteWorks AI Labs", location: "Bangalore" },
  //     { id: 10, name: "AgroFuture Industries", location: "Ahmedabad" },
  //   ];
  //   await db.insert(schema.organizations).values(organization_data);
  //   console.log("Inserted into Orgaization table.");
  //   const departments_data = [
  //     { id: 1, name: "Human Resources", organizationId: 1 },
  //     { id: 2, name: "Engineering", organizationId: 1 },
  //     { id: 3, name: "Finance", organizationId: 1 },
  //     { id: 4, name: "Marketing", organizationId: 1 },
  //     { id: 5, name: "Admissions", organizationId: 2 },
  //     { id: 6, name: "Academics", organizationId: 2 },
  //     { id: 7, name: "Research & Development", organizationId: 2 },
  //     { id: 8, name: "IT Support", organizationId: 2 },
  //     { id: 9, name: "Medical Staff", organizationId: 3 },
  //     { id: 10, name: "Pharmacy", organizationId: 3 },
  //     { id: 11, name: "Administration", organizationId: 3 },
  //     { id: 12, name: "Patient Care", organizationId: 3 },
  //     { id: 13, name: "Flight Operations", organizationId: 4 },
  //     { id: 14, name: "Maintenance", organizationId: 4 },
  //     { id: 15, name: "Safety & Compliance", organizationId: 4 },
  //     { id: 16, name: "Ground Services", organizationId: 4 },
  //     { id: 17, name: "Production", organizationId: 5 },
  //     { id: 18, name: "Supply Chain", organizationId: 5 },
  //     { id: 19, name: "Quality Control", organizationId: 5 },
  //     { id: 20, name: "Sales & Distribution", organizationId: 5 },
  //     { id: 21, name: "Customer Support", organizationId: 6 },
  //     { id: 22, name: "Finance & Accounts", organizationId: 6 },
  //     { id: 23, name: "IT & Cybersecurity", organizationId: 6 },
  //     { id: 24, name: "Product Strategy", organizationId: 6 },
  //     { id: 25, name: "Property Sales", organizationId: 7 },
  //     { id: 26, name: "Design & Architecture", organizationId: 7 },
  //     { id: 27, name: "Legal Affairs", organizationId: 7 },
  //     { id: 28, name: "Client Relations", organizationId: 7 },
  //     { id: 29, name: "Film Production", organizationId: 8 },
  //     { id: 30, name: "Editing & Post Production", organizationId: 8 },
  //     { id: 31, name: "Creative Direction", organizationId: 8 },
  //     { id: 32, name: "Marketing & PR", organizationId: 8 },
  //     { id: 33, name: "AI Research", organizationId: 9 },
  //     { id: 34, name: "Software Engineering", organizationId: 9 },
  //     { id: 35, name: "Data Science", organizationId: 9 },
  //     { id: 36, name: "Operations", organizationId: 9 },
  //     { id: 37, name: "Crop Science", organizationId: 10 },
  //     { id: 38, name: "Machinery", organizationId: 10 },
  //     { id: 39, name: "Logistics", organizationId: 10 },
  //     { id: 40, name: "Research & Innovation", organizationId: 10 },
  //   ];
  //   await db.insert(schema.departments).values(departments_data);
  //   console.log("Inserted into the Departments Table.");
  const users_data = [
    {
      id: 1,
      orgEmpId: "ADM-TNS-1",
      firstName: "Priya",
      lastName: "Rao",
      email: "priya.rao@technova.com",
      password: "hashedpassword123",
      contactNo: "9876500001",
      role: "admin",
      address: "Koramangala, Bangalore",
      joiningDate: "2024-02-10",
    },
    {
      id: 2,
      orgEmpId: "ADM-TNS-2",
      firstName: "Rohit",
      lastName: "Menon",
      email: "rohit.menon@technova.com",
      password: "hashedpassword123",
      contactNo: "9876500002",
      role: "admin",
      address: "HSR Layout, Bangalore",
      joiningDate: "2023-11-15",
    },
    {
      id: 3,
      orgEmpId: "ADM-TNS-3",
      firstName: "Anjali",
      lastName: "Deshmukh",
      email: "anjali.deshmukh@technova.com",
      password: "hashedpassword123",
      contactNo: "9876500003",
      role: "admin",
      address: "Indiranagar, Bangalore",
      joiningDate: "2024-01-05",
    },
    {
      id: 4,
      orgEmpId: "ADM-TNS-4",
      firstName: "Arun",
      lastName: "Sethi",
      email: "arun.sethi@technova.com",
      password: "hashedpassword123",
      contactNo: "9876500004",
      role: "admin",
      address: "Whitefield, Bangalore",
      joiningDate: "2024-03-01",
    },

    {
      id: 5,
      orgEmpId: "ADM-EDU-1",
      firstName: "Kavita",
      lastName: "Joshi",
      email: "kavita.joshi@edusphere.edu",
      password: "hashedpassword123",
      contactNo: "9876500005",
      role: "admin",
      address: "Baner, Pune",
      joiningDate: "2024-04-10",
    },
    {
      id: 6,
      orgEmpId: "ADM-EDU-2",
      firstName: "Nikhil",
      lastName: "Patil",
      email: "nikhil.patil@edusphere.edu",
      password: "hashedpassword123",
      contactNo: "9876500006",
      role: "admin",
      address: "Kothrud, Pune",
      joiningDate: "2023-12-02",
    },
    {
      id: 7,
      orgEmpId: "ADM-EDU-3",
      firstName: "Sneha",
      lastName: "Bhatia",
      email: "sneha.bhatia@edusphere.edu",
      password: "hashedpassword123",
      contactNo: "9876500007",
      role: "admin",
      address: "Wakad, Pune",
      joiningDate: "2024-01-25",
    },
    {
      id: 8,
      orgEmpId: "ADM-EDU-4",
      firstName: "Rahul",
      lastName: "Verma",
      email: "rahul.verma@edusphere.edu",
      password: "hashedpassword123",
      contactNo: "9876500008",
      role: "admin",
      address: "Viman Nagar, Pune",
      joiningDate: "2023-10-18",
    },

    {
      id: 9,
      orgEmpId: "ADM-HBH-1",
      firstName: "Meera",
      lastName: "Kaur",
      email: "meera.kaur@healthbridge.com",
      password: "hashedpassword123",
      contactNo: "9876500009",
      role: "admin",
      address: "Banjara Hills, Hyderabad",
      joiningDate: "2024-02-15",
    },
    {
      id: 10,
      orgEmpId: "ADM-HBH-2",
      firstName: "Rajesh",
      lastName: "Iyer",
      email: "rajesh.iyer@healthbridge.com",
      password: "hashedpassword123",
      contactNo: "9876500010",
      role: "admin",
      address: "Jubilee Hills, Hyderabad",
      joiningDate: "2024-01-20",
    },
    {
      id: 11,
      orgEmpId: "ADM-HBH-3",
      firstName: "Divya",
      lastName: "Pillai",
      email: "divya.pillai@healthbridge.com",
      password: "hashedpassword123",
      contactNo: "9876500011",
      role: "admin",
      address: "Madhapur, Hyderabad",
      joiningDate: "2023-11-30",
    },
    {
      id: 12,
      orgEmpId: "ADM-HBH-4",
      firstName: "Amit",
      lastName: "Chandra",
      email: "amit.chandra@healthbridge.com",
      password: "hashedpassword123",
      contactNo: "9876500012",
      role: "admin",
      address: "Kondapur, Hyderabad",
      joiningDate: "2024-03-05",
    },

    {
      id: 13,
      orgEmpId: "ADM-AER-1",
      firstName: "Simran",
      lastName: "Gill",
      email: "simran.gill@aerolink.com",
      password: "hashedpassword123",
      contactNo: "9876500013",
      role: "admin",
      address: "Andheri East, Mumbai",
      joiningDate: "2024-02-08",
    },
    {
      id: 14,
      orgEmpId: "ADM-AER-2",
      firstName: "Vikas",
      lastName: "Reddy",
      email: "vikas.reddy@aerolink.com",
      password: "hashedpassword123",
      contactNo: "9876500014",
      role: "admin",
      address: "Vile Parle, Mumbai",
      joiningDate: "2023-12-01",
    },
    {
      id: 15,
      orgEmpId: "ADM-AER-3",
      firstName: "Neha",
      lastName: "Kapoor",
      email: "neha.kapoor@aerolink.com",
      password: "hashedpassword123",
      contactNo: "9876500015",
      role: "admin",
      address: "Bandra, Mumbai",
      joiningDate: "2024-01-18",
    },
    {
      id: 16,
      orgEmpId: "ADM-AER-4",
      firstName: "Suresh",
      lastName: "Malhotra",
      email: "suresh.malhotra@aerolink.com",
      password: "hashedpassword123",
      contactNo: "9876500016",
      role: "admin",
      address: "Santacruz, Mumbai",
      joiningDate: "2024-03-02",
    },

    {
      id: 17,
      orgEmpId: "ADM-GLO-1",
      firstName: "Pooja",
      lastName: "Das",
      email: "pooja.das@greenleaf.com",
      password: "hashedpassword123",
      contactNo: "9876500017",
      role: "admin",
      address: "Salt Lake, Kolkata",
      joiningDate: "2024-01-12",
    },
    {
      id: 18,
      orgEmpId: "ADM-GLO-2",
      firstName: "Abhishek",
      lastName: "Nair",
      email: "abhishek.nair@greenleaf.com",
      password: "hashedpassword123",
      contactNo: "9876500018",
      role: "admin",
      address: "New Town, Kolkata",
      joiningDate: "2023-12-22",
    },
    {
      id: 19,
      orgEmpId: "ADM-GLO-3",
      firstName: "Shalini",
      lastName: "Roy",
      email: "shalini.roy@greenleaf.com",
      password: "hashedpassword123",
      contactNo: "9876500019",
      role: "admin",
      address: "Behala, Kolkata",
      joiningDate: "2024-02-20",
    },
    {
      id: 20,
      orgEmpId: "ADM-GLO-4",
      firstName: "Karan",
      lastName: "Chakraborty",
      email: "karan.chakraborty@greenleaf.com",
      password: "hashedpassword123",
      contactNo: "9876500020",
      role: "admin",
      address: "Dum Dum, Kolkata",
      joiningDate: "2024-03-08",
    },

    {
      id: 21,
      orgEmpId: "ADM-NFS-1",
      firstName: "Ritika",
      lastName: "Singh",
      email: "ritika.singh@nextgenfinance.com",
      password: "hashedpassword123",
      contactNo: "9876500021",
      role: "admin",
      address: "Connaught Place, Delhi",
      joiningDate: "2023-11-12",
    },
    {
      id: 22,
      orgEmpId: "ADM-NFS-2",
      firstName: "Dev",
      lastName: "Bansal",
      email: "dev.bansal@nextgenfinance.com",
      password: "hashedpassword123",
      contactNo: "9876500022",
      role: "admin",
      address: "Saket, Delhi",
      joiningDate: "2024-02-14",
    },
    {
      id: 23,
      orgEmpId: "ADM-NFS-3",
      firstName: "Anita",
      lastName: "Mishra",
      email: "anita.mishra@nextgenfinance.com",
      password: "hashedpassword123",
      contactNo: "9876500023",
      role: "admin",
      address: "Dwarka, Delhi",
      joiningDate: "2024-01-08",
    },
    {
      id: 24,
      orgEmpId: "ADM-NFS-4",
      firstName: "Tarun",
      lastName: "Gupta",
      email: "tarun.gupta@nextgenfinance.com",
      password: "hashedpassword123",
      contactNo: "9876500024",
      role: "admin",
      address: "Rohini, Delhi",
      joiningDate: "2024-03-03",
    },

    {
      id: 25,
      orgEmpId: "ADM-UHR-1",
      firstName: "Aisha",
      lastName: "Khan",
      email: "aisha.khan@urbanhomes.com",
      password: "hashedpassword123",
      contactNo: "9876500025",
      role: "admin",
      address: "T Nagar, Chennai",
      joiningDate: "2024-02-25",
    },
    {
      id: 26,
      orgEmpId: "ADM-UHR-2",
      firstName: "Vivek",
      lastName: "Raman",
      email: "vivek.raman@urbanhomes.com",
      password: "hashedpassword123",
      contactNo: "9876500026",
      role: "admin",
      address: "Velachery, Chennai",
      joiningDate: "2024-01-16",
    },
    {
      id: 27,
      orgEmpId: "ADM-UHR-3",
      firstName: "Tanya",
      lastName: "Dey",
      email: "tanya.dey@urbanhomes.com",
      password: "hashedpassword123",
      contactNo: "9876500027",
      role: "admin",
      address: "Adyar, Chennai",
      joiningDate: "2023-12-10",
    },
    {
      id: 28,
      orgEmpId: "ADM-UHR-4",
      firstName: "Rohan",
      lastName: "Sarkar",
      email: "rohan.sarkar@urbanhomes.com",
      password: "hashedpassword123",
      contactNo: "9876500028",
      role: "admin",
      address: "Anna Nagar, Chennai",
      joiningDate: "2024-03-06",
    },

    {
      id: 29,
      orgEmpId: "ADM-CWS-1",
      firstName: "Naina",
      lastName: "Bose",
      email: "naina.bose@cinewave.com",
      password: "hashedpassword123",
      contactNo: "9876500029",
      role: "admin",
      address: "Andheri West, Mumbai",
      joiningDate: "2023-11-25",
    },
    {
      id: 30,
      orgEmpId: "ADM-CWS-2",
      firstName: "Sanjay",
      lastName: "Chopra",
      email: "sanjay.chopra@cinewave.com",
      password: "hashedpassword123",
      contactNo: "9876500030",
      role: "admin",
      address: "Goregaon, Mumbai",
      joiningDate: "2024-02-05",
    },
    {
      id: 31,
      orgEmpId: "ADM-CWS-3",
      firstName: "Leena",
      lastName: "Ghosh",
      email: "leena.ghosh@cinewave.com",
      password: "hashedpassword123",
      contactNo: "9876500031",
      role: "admin",
      address: "Powai, Mumbai",
      joiningDate: "2024-01-12",
    },
    {
      id: 32,
      orgEmpId: "ADM-CWS-4",
      firstName: "Ajay",
      lastName: "Malik",
      email: "ajay.malik@cinewave.com",
      password: "hashedpassword123",
      contactNo: "9876500032",
      role: "admin",
      address: "Bandra West, Mumbai",
      joiningDate: "2024-03-04",
    },

    {
      id: 33,
      orgEmpId: "ADM-BWL-1",
      firstName: "Sonia",
      lastName: "Dasgupta",
      email: "sonia.dasgupta@byteworks.ai",
      password: "hashedpassword123",
      contactNo: "9876500033",
      role: "admin",
      address: "Koramangala, Bangalore",
      joiningDate: "2023-12-20",
    },
    {
      id: 34,
      orgEmpId: "ADM-BWL-2",
      firstName: "Harsh",
      lastName: "Rathore",
      email: "harsh.rathore@byteworks.ai",
      password: "hashedpassword123",
      contactNo: "9876500034",
      role: "admin",
      address: "BTM Layout, Bangalore",
      joiningDate: "2024-01-22",
    },
    {
      id: 35,
      orgEmpId: "ADM-BWL-3",
      firstName: "Manisha",
      lastName: "Khatri",
      email: "manisha.khatri@byteworks.ai",
      password: "hashedpassword123",
      contactNo: "9876500035",
      role: "admin",
      address: "Indiranagar, Bangalore",
      joiningDate: "2024-02-28",
    },
    {
      id: 36,
      orgEmpId: "ADM-BWL-4",
      firstName: "Gaurav",
      lastName: "Bhattacharjee",
      email: "gaurav.bhattacharjee@byteworks.ai",
      password: "hashedpassword123",
      contactNo: "9876500036",
      role: "admin",
      address: "Marathahalli, Bangalore",
      joiningDate: "2024-03-10",
    },

    {
      id: 37,
      orgEmpId: "ADM-AFI-1",
      firstName: "Deepa",
      lastName: "Naidu",
      email: "deepa.naidu@agrofuture.com",
      password: "hashedpassword123",
      contactNo: "9876500037",
      role: "admin",
      address: "Navrangpura, Ahmedabad",
      joiningDate: "2024-01-09",
    },
    {
      id: 38,
      orgEmpId: "ADM-AFI-2",
      firstName: "Sameer",
      lastName: "Trivedi",
      email: "sameer.trivedi@agrofuture.com",
      password: "hashedpassword123",
      contactNo: "9876500038",
      role: "admin",
      address: "Bopal, Ahmedabad",
      joiningDate: "2024-02-16",
    },
    {
      id: 39,
      orgEmpId: "ADM-AFI-3",
      firstName: "Pallavi",
      lastName: "Joshi",
      email: "pallavi.joshi@agrofuture.com",
      password: "hashedpassword123",
      contactNo: "9876500039",
      role: "admin",
      address: "Maninagar, Ahmedabad",
      joiningDate: "2023-11-27",
    },
    {
      id: 40,
      orgEmpId: "ADM-AFI-4",
      firstName: "Ramesh",
      lastName: "Patel",
      email: "ramesh.patel@agrofuture.com",
      password: "hashedpassword123",
      contactNo: "9876500040",
      role: "admin",
      address: "Thaltej, Ahmedabad",
      joiningDate: "2024-03-12",
    },
  ];
  const newUserData = await hashUserPassword(users_data);
  await db.insert(schema.users).values(newUserData);
  console.log("Inserted into the departments table.");
  const admins_data = [
    { adminId: 1, manages: 1 },
    { adminId: 2, manages: 2 },
    { adminId: 3, manages: 3 },
    { adminId: 4, manages: 4 },

    { adminId: 5, manages: 5 },
    { adminId: 6, manages: 6 },
    { adminId: 7, manages: 7 },
    { adminId: 8, manages: 8 },

    { adminId: 9, manages: 9 },
    { adminId: 10, manages: 10 },
    { adminId: 11, manages: 11 },
    { adminId: 12, manages: 12 },

    { adminId: 13, manages: 13 },
    { adminId: 14, manages: 14 },
    { adminId: 15, manages: 15 },
    { adminId: 16, manages: 16 },

    { adminId: 17, manages: 17 },
    { adminId: 18, manages: 18 },
    { adminId: 19, manages: 19 },
    { adminId: 20, manages: 20 },

    { adminId: 21, manages: 21 },
    { adminId: 22, manages: 22 },
    { adminId: 23, manages: 23 },
    { adminId: 24, manages: 24 },

    { adminId: 25, manages: 25 },
    { adminId: 26, manages: 26 },
    { adminId: 27, manages: 27 },
    { adminId: 28, manages: 28 },

    { adminId: 29, manages: 29 },
    { adminId: 30, manages: 30 },
    { adminId: 31, manages: 31 },
    { adminId: 32, manages: 32 },

    { adminId: 33, manages: 33 },
    { adminId: 34, manages: 34 },
    { adminId: 35, manages: 35 },
    { adminId: 36, manages: 36 },

    { adminId: 37, manages: 37 },
    { adminId: 38, manages: 38 },
    { adminId: 39, manages: 39 },
    { adminId: 40, manages: 40 },
  ];
  await db.insert(schema.admins).values(admins_data);
  console.log("Inserted into the Admins table . ");
  const users_record_data = [
    { id: 1, organizationId: 1, departmentId: 1 },
    { id: 2, organizationId: 1, departmentId: 2 },
    { id: 3, organizationId: 1, departmentId: 3 },
    { id: 4, organizationId: 1, departmentId: 4 },

    { id: 5, organizationId: 2, departmentId: 5 },
    { id: 6, organizationId: 2, departmentId: 6 },
    { id: 7, organizationId: 2, departmentId: 7 },
    { id: 8, organizationId: 2, departmentId: 8 },

    { id: 9, organizationId: 3, departmentId: 9 },
    { id: 10, organizationId: 3, departmentId: 10 },
    { id: 11, organizationId: 3, departmentId: 11 },
    { id: 12, organizationId: 3, departmentId: 12 },

    { id: 13, organizationId: 4, departmentId: 13 },
    { id: 14, organizationId: 4, departmentId: 14 },
    { id: 15, organizationId: 4, departmentId: 15 },
    { id: 16, organizationId: 4, departmentId: 16 },

    { id: 17, organizationId: 5, departmentId: 17 },
    { id: 18, organizationId: 5, departmentId: 18 },
    { id: 19, organizationId: 5, departmentId: 19 },
    { id: 20, organizationId: 5, departmentId: 20 },

    { id: 21, organizationId: 6, departmentId: 21 },
    { id: 22, organizationId: 6, departmentId: 22 },
    { id: 23, organizationId: 6, departmentId: 23 },
    { id: 24, organizationId: 6, departmentId: 24 },

    { id: 25, organizationId: 7, departmentId: 25 },
    { id: 26, organizationId: 7, departmentId: 26 },
    { id: 27, organizationId: 7, departmentId: 27 },
    { id: 28, organizationId: 7, departmentId: 28 },

    { id: 29, organizationId: 8, departmentId: 29 },
    { id: 30, organizationId: 8, departmentId: 30 },
    { id: 31, organizationId: 8, departmentId: 31 },
    { id: 32, organizationId: 8, departmentId: 32 },

    { id: 33, organizationId: 9, departmentId: 33 },
    { id: 34, organizationId: 9, departmentId: 34 },
    { id: 35, organizationId: 9, departmentId: 35 },
    { id: 36, organizationId: 9, departmentId: 36 },

    { id: 37, organizationId: 10, departmentId: 37 },
    { id: 38, organizationId: 10, departmentId: 38 },
    { id: 39, organizationId: 10, departmentId: 39 },
    { id: 40, organizationId: 10, departmentId: 40 },
  ];
  await db.insert(schema.userRecords).values(users_record_data);
  console.log("Inserted the users_record_data.");
  const leavetype_data = [
    {
      id: 1,
      name: "Casual Leave",
      description:
        "Short-term leave for personal reasons such as family functions, unforeseen errands, or emergencies. Typically pre-approved and limited to a few days per instance.",
      maxDaysPerYear: 12,
    },
    {
      id: 2,
      name: "Sick Leave",
      description:
        "Granted when the employee is unwell or attending medical treatment. Requires a doctor’s note if taken for more than two consecutive days.",
      maxDaysPerYear: 10,
    },
    {
      id: 3,
      name: "Earned Leave",
      description:
        "Leave accumulated over time for planned vacations or extended breaks. Can be carried forward or encashed as per company policy.",
      maxDaysPerYear: 15,
    },
    {
      id: 4,
      name: "Maternity Leave",
      description:
        "Leave provided to expectant mothers for childbirth, prenatal and postnatal care. Typically lasts for six months with full pay.",
      maxDaysPerYear: 180,
    },
    {
      id: 5,
      name: "Compensatory Leave",
      description:
        "Time off given to employees who worked on weekends, holidays, or beyond normal hours. Compensates for overtime effort.",
      maxDaysPerYear: 5,
    },
  ];
  await db.insert(schema.leaveTypes).values(leavetype_data);
  console.log("Inserted into leave_type table.");
}

console.log("Check seed file before seeing next data...");
// seed();
